package model

import "time"

// OAuthResponseType represents the different types of response types available
// during OAuth authorization phase.
type OAuthResponseType string

const (
	// CodeResponseType is the response type for the Authorization phase of the
	// Authorization Code flow.
	CodeResponseType = OAuthResponseType("code")
)

// OAuthCodeChallengeMethod represents the different methods for code challenge
// in the PKCE extension of the Authorization Code flow.
type OAuthCodeChallengeMethod string

const (
	// PlainCodeChallengeMethod is the code_challenge_method when the code verifier
	// is sent as-is to the server.
	PlainCodeChallengeMethod = OAuthCodeChallengeMethod("plain")
	// S256CodeChallengeMethod is the code_challenge_method when the code verifier
	// is sent as a Base64 URL encoded hash to the server.
	S256CodeChallengeMethod = OAuthCodeChallengeMethod("S256")
)

// OAuthAuthorizeInput is the model for OAuth Authorization requests. It contains all
// the parameters which may be required. Implementations must validate the parameters
// depending on the response type.
type OAuthAuthorizeInput struct {
	// Unique ID of the Client who requests authorization to act on behalf of the user.
	ClientID string

	// URI where the user must be redirected with the authorization code in order to
	// continue the OAuth flow. This must match the one stored when the client was
	// registered.
	RedirectURI string

	// Type of the expected response depending on the authorization flow
	// (only "code" is available).
	ResponseType OAuthResponseType

	// Optional state string which will be returned to the client in the callback.
	State string

	// Optional space separated string indicating the access scopes requested by the client.
	Scope string `json:"scope,omitempty"`

	// (PKCE Extension) Optional code challenge generated by the client so it can
	// avoid sending the client_secret to request a token. The client generates a
	// "code verifier" as a random string and then it sends this code verifier either
	// as a Base64 URL encoded SHA-256 hash or as plain text. This code will be sent
	// again in the token request to ensure that the request comes from the authorized
	// client.
	CodeChallenge string

	// (PKCE Extension) Optional method for the given code challenge. It can either be
	// 'plain' (the client has sent the code verifier) or 'S256' (the client has sent
	// a Base64 URL encoded SHA-256 hash of the code verifier)
	CodeChallengeMethod OAuthCodeChallengeMethod
}

// OAuthAuthorizeResponse is the response sent back by the Authorization Server
// when an OAuth authorization request is performed.
type OAuthAuthorizeResponse struct {
	// Authorization Code sent to the callback so it can be used to obtain an access
	// token. Contents are encrypted so only the Authorization Server can access the
	// token information.
	Code string `json:"code" validate:"required"`

	// URL of the client where the UI should redirect the user to complete the
	// authorization flow. This url contains all the required query params.
	RedirectURI string `json:"redirect_uri" validate:"required,url"`
}

// OAuthAuthorizationCode is the model for the Authorization Code token used in the
// Authorization Code Flow. Token providers are responsible for serializing/deserializing
// from/to this structure.
type OAuthAuthorizationCode struct {
	// Unique UUID for the authorization code. This code should be checked against a repository
	// so authorization codes are only used once.
	TokenID string

	// ID of the user (Resource Owner) who authorizes the client to obtain
	// a token on his behalf.
	UserID string

	// ID of the Client who has requested authorization to act on behalf of
	// the user.
	ClientID string

	// URL that the Client has set as callback when requesting authorization.
	// This URL must match the one passed in when requesting an access token.
	RedirectURI string

	// Optional space separated string indicating the access scopes requested by the client.
	Scope string

	// Time when the authorization code expires and can't be used.
	ExpirationTime time.Time

	// Base64 URL encoded code verifier that the client sets during authorization
	// to be checked later when obtaining an access token.
	CodeChallenge string
}
